[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200
monitor_filters = default

; Upload options
upload_speed = 921600

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3

; Libraries
lib_deps = 
    knolleary/PubSubClient@^2.8


